// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZyhnUgh8H-a23B2e-O2Vb5QDEGT-e4E',
    appId: '1:897458318180:web:14a7bd813f172ac4db2871',
    messagingSenderId: '897458318180',
    projectId: 'speed-guardian',
    authDomain: 'speed-guardian.firebaseapp.com',
    storageBucket: 'speed-guardian.appspot.com',
    measurementId: 'G-V3PQZ5TJWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64JyRUYdRQiUs56gTp0giP_8kDCQKnkI',
    appId: '1:897458318180:android:60dad5e9215d7a93db2871',
    messagingSenderId: '897458318180',
    projectId: 'speed-guardian',
    storageBucket: 'speed-guardian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzas8t0u59tbX4q3bh6IyFfJa4is1fStI',
    appId: '1:897458318180:ios:85da6fa87ee1b6d1db2871',
    messagingSenderId: '897458318180',
    projectId: 'speed-guardian',
    storageBucket: 'speed-guardian.appspot.com',
    iosBundleId: 'com.example.speedGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzas8t0u59tbX4q3bh6IyFfJa4is1fStI',
    appId: '1:897458318180:ios:f5d49495d7a8af10db2871',
    messagingSenderId: '897458318180',
    projectId: 'speed-guardian',
    storageBucket: 'speed-guardian.appspot.com',
    iosBundleId: 'com.example.speedGuardian.RunnerTests',
  );
}
